

struct DTC_struct {
  const char *szCode;
  const char *szDescr;
};

const struct DTC_struct g_Known_DTCs[] = {
    {"A1-1x", "Faulty Power Supply VA Line"},
    {"A2-1x", "Faulty Power Supply VB Line"},
    {"D1-11", "Driver Air Bag Module And Seat Belt Tensioner Deployed"},
    {"D2-11", "Passenger Air Bag Module And Seat Belt Tensioner Deployed"},
    {"D3-11", "Driver Air Bag Module Deployed"},
    {"D4-11", "Passenger Air Bag Module Deployed"},
    {"D7-11", "Rear End Collision"},
    {"E4-11", "Passenger Side Impact Air Bag Module Deployed"},
    {"F1-11", "Driver Air Bag Module And Seat Belt Tensioner Deployed"},
    {"F2-11", "Passenger Air Bag Module And Seat Belt Tensioner Deployed"},
    {"F3-11", "Driver Side Impact Air Bag Module Deployed"},
    {"F4-11", "Passenger Side Impact Air Bag Module Deployed"},
    {"11-Ax", "short circuited To Power In Driver Air Bag Second Module"},
    {"11-Bx", "short circuited To Ground In Driver Air Bag Second Module"},
    {"11-1x", "open circuited Or high Resistance In Driver Air Bag Module"},
    {"11-3x", "short circuited To Another Wire Or low Resistance In Driver Air "
              "Bag Module"},
    {"11-4x",
     "open circuited Or high Resistance In Driver Air Bag Second Module"},
    {"11-5x", "high Resistance In Driver Air Bag Second Module"},
    {"11-6x", "short circuited To Another Wire Or low Resistance In Driver Air "
              "Bag Second Module"},
    {"11-8x", "short circuited To Power In Driver Air Bag First Module"},
    {"11-9x", "short circuited To Ground In Driver Air Bag First Module"},
    {"12-Ax", "short circuited To Power In Passenger Air Bag Second Module"},
    {"12-Bx", "short circuited To Ground In Passenger Air Bag Second Module"},
    {"12-1x",
     "open circuited Or high Resistance In Passenger Air Bag First Module"},
    {"12-2x", "high Resistance In Passenger Air Bag First Module"},
    {"12-3x", "short circuited To Another Wire Or low Resistance In Passenger "
              "Air Bag First Module"},
    {"12-4x",
     "open circuited Or high Resistance In Passenger Air Bag Second Module"},
    {"12-5x", "high Resistance In Passenger Air Bag Second Module"},
    {"12-6x", "short circuited To Another Wire Or low Resistance In Passenger "
              "Air Bag Second Module"},
    {"12-8x", "short circuited To Power In Passenger Air Bag First Module"},
    {"12-9x", "short circuited To Ground In Passenger Air Bag First Module"},
    {"21-1x",
     "open circuited Or high Resistance In Driver Seat Belt Tensioner"},
    {"21-2x", "high Resistance In Driver Seat Belt Tensioner"},
    {"21-3x", "short circuited To Another Wire Or low Resistance In Driver "
              "Seat Belt Tensioner"},
    {"21-8x", "short circuited To Power In Driver Seat Belt Tensioner"},
    {"21-9x", "short circuited To Ground In Driver Seat Belt Tensioner"},
    {"22-1x",
     "open circuited Or high Resistance In Passenger Seat Belt Tensioner"},
    {"22-2x", "high Resistance In Passenger Seat Belt Tensioner"},
    {"22-3x", "short circuited To Another Wire Or low Resistance In Passenger "
              "Seat Belt Tensioner"},
    {"22-8x", "short circuited To Power In Passenger Seat Belt Tensioner"},
    {"22-9x", "short circuited To Ground In Passenger Seat Belt Tensioner"},
    {"31-ix",
     "open circuited Or high Resistance In Driver Side Impact Air Bag Module"},
    {"31-2x", "high Resistance In Driver Side Impact Air Bag Module"},
    {"31-3x", "short circuited To Another Wire Or low Resistance In Driver "
              "Side Impact Air Bag Module"},
    {"31-8x", "short circuited To Power In Driver Side Impact Air Bag Module"},
    {"31-9x", "short circuited To Ground In Driver Side Impact Air Bag Module"},
    {"32-1x", "open circuited Or high Resistance In Front Passenger Side "
              "Impact Air Bag Module"},
    {"32-2x", "high Resistance In Passenger Side Impact Air Bag Module"},
    {"32-3x", "short circuited To Another Wire Or low Resistance In Passenger "
              "Side Impact Air Bag Module"},
    {"32-8x",
     "short circuited To Power In Passenger Side Impact Air Bag Module"},
    {"32-9x",
     "short circuited To Ground In Passenger Side Impact Air Bag Module"},
    {"33-1x",
     "open circuited Or high Resistance In Driver Roof Panel Air Bag Module"},
    {"33-3x", "short circuited To Another Wire Or low Resistance In Driver "
              "Roof Panel Air Bag Module"},
    {"33-8x", "short circuited To Power In Driver Roof Panel Air Bag Module"},
    {"33-9x", "short circuited To Ground In Driver Roof Panel Air Bag Module"},
    {"34-ix", "open circuited Or high Resistance In Passenger Roof Panel Air "
              "Bag Module"},
    {"34-3x", "short circuited To Another Wire Or low Resistance In Passenger "
              "Roof Panel Air Bag Module"},
    {"34-8x",
     "short circuited To Power In Passenger Roof Panel Air Bag Module"},
    {"34-9x",
     "short circuited To Ground In Passenger Roof Panel Air Bag Module"},
    {"41-Cx", "Faulty Power Supply To Driver Front Impact Sensor"},
    {"41-1x", "No Signal From Driver Front Impact Sensor"},
    {"41-2x,", "Internal Failure Of Driver Front Impact Sensor"},
    {"41-3x", "Internal Failure Of Driver Front Impact Sensor"},
    {"41-9x", "Faulty Power Supply To Passenger Front Impact Sensor"},
    {"41-Bx", "Faulty Power Supply To Passenger Front Impact Sensor"},
    {"42-Cx", "Faulty Power Supply To Passenger Front Impact Sensor"},
    {"42-1x", "No Signal From Passenger Front Impact Sensor"},
    {"42-2x,", "Internal Failure Of Passenger Front Impact Sensor"},
    {"42-3x", "Internal Failure Of Passenger Front Impact Sensor"},
    {"42-9x", "Internal Failure Of Passenger Front Impact Sensor"},
    {"42-Bx", "Internal Failure Of Passenger Front Impact Sensor"},
    {"43-Cx", "Faulty Power Supply To Driver Side Impact Sensor"},
    {"43-1x", "No Signal From Driver Side Impact Sensor"},
    {"43-xx,", "Internal Failure Of Driver Side Impact Sensor"},
    {"44-Cx", "Faulty Power Supply To Passenger Side Impact Sensor"},
    {"44-1x", "No Signal From Passenger Side Impact Sensor"},
    {"44-xx", "Internal Failure Of Passenger Side Impact Sensor"},
    {"56-11", "PCM connection failure"},
    {"56-21", "PCM connection failure"},
    {"56-25", "CAN connection with Meter"},
    {"56-26", "CAN data invalid with Meter"},
    {"5x-xx", "Internal Failure Of SRS Unit"},
    {"61-1x", "open circuited In Driver Seat Belt Buckle Switch"},
    {"61-2x", "short circuited In Driver Seat Belt Buckle Switch"},
    {"62-1x", "open circuited In Passenger Seat Belt Buckle Switch"},
    {"62-2x", "short circuited In Passenger Seat Belt Buckle Switch"},
    {"85-4x", "Faulty OPDS Unit"},
    {"85-5x", "Faulty OPDS Unit"},
    {"85-61", "No Signal From OPDS Unit"},
    {"85-62", "Non-Stipulated Response Data"},
    {"85-63", "Model ID Code Or Variation Code Inconsistent"},
    {"85-64", "ECU Serial ID Code Inconsistent"},
    {"85-71", "OPDS Unit Not Initialized"},
    {"85-78", "OPDS Unit Not Initialized"},
    {"85-79", "OPDS Drift Check Failure"},
    {"86-lx", "Faulty Seat Back OPDS Sensor"},
    {"86-2x", "Faulty Seat Support OPDS Sensor"},
    {"87-31", "Internal Failure Of SRS Unit"},
    {"87-32", "Side Impact Air Bag Cutoff Indicator Stays On"},
    {"91-1x", "Internal Failure Of SRS Unit"},
    {"91-2x", "short circuited In SRS Indicator Circuit"}};